### ISSUE TITLE
Raspberry Pi 4: Wrong Thunderbird language and remote resizing not working

### ISSUE THREAD

**Issue by CountCypher** [ich777/docker-thunderbird#16]
Hi there!

First of all, thanks for your work on this. Very useful project! 👍

I'm running the container on a Raspberry Pi 4 (Debian Bullseye) with `docker compose`:

```
version: '3.3'
services:
    thunderbird:
        image: ich777/thunderbird
        container_name: thunderbird
        restart: unless-stopped
        ports:
            - '8091:8080'
        environment:
            - THUNDERBIRD_V=latest
            - THUNDERBIRD_LANG=de
            - 'TURBOVNC_PARAMS=-securitytypes none'
            - CUSTOM_RES_W=1280
            - CUSTOM_RES_H=768
            - UID=1000
            - GID=1000
            - UMASK=000
            - DATA_PERM=770
        volumes:
            - './thunderbird:/thunderbird'
        security_opt:
            - no-new-privileges:true
```
The problem I have is 1) Even though I have defined the German language for Thunderbird, it seems to have loaded the English version. And 2) Remote resizing is not working.

![Screenshot 2023-06-06 145208](https://github.com/ich777/docker-thunderbird/assets/54265000/eb755629-a20d-4326-9d2b-77b69d8deec1)

Here's the docker container log:

```
thunderbird  | ---Ensuring UID: 1000 matches user---
thunderbird  | usermod: no changes
thunderbird  | ---Ensuring GID: 1000 matches user---
thunderbird  | usermod: no changes
thunderbird  | ---Setting umask to 000---
thunderbird  | ---Checking for optional scripts---
thunderbird  | ---No optional script found, continuing---
thunderbird  | ---Checking configuration for noVNC---
thunderbird  | Nothing to do, noVNC resizing set to default
thunderbird  | Nothing to do, noVNC qaulity set to default
thunderbird  | Nothing to do, noVNC compression set to default
thunderbird  | ---Taking ownership of data...---
thunderbird  | ---Starting...---
thunderbird  | ---Preparing Server---
thunderbird  | ---Resolution check---
thunderbird  | ---Checking for old logfiles---
thunderbird  | ---Checking for old display lock files---
thunderbird  | ---Starting Xvfb server---
thunderbird  | ---Starting x11vnc server---
thunderbird  | ---Starting Fluxbox---
thunderbird  | ---Starting noVNC server---
thunderbird  | WebSocket server settings:
thunderbird  |   - Listen on :8080
thunderbird  |   - Web server. Web root: /usr/share/novnc
thunderbird  |   - No SSL/TLS support (no cert file)
thunderbird  |   - Backgrounding (daemon)
thunderbird  | ---Starting Thunderbird---
thunderbird  | [GFX1-]: glxtest: libpci missing
thunderbird  | [Parent 77, Main Thread] WARNING: Failed to execute child process “update-desktop-database” (No such file or directory): 'glib warning', file ./toolkit/xre/nsSigHandlers.cpp:167
thunderbird  | 
thunderbird  | (thunderbird-default:77): GLib-GIO-WARNING **: 14:24:19.515: Failed to execute child process “update-desktop-database” (No such file or directory)
```
Not sure if this helps in troubleshooting:
I'm running the container also on a Proxmox amd64 LXC with Debian Bullseye. There the two mentioned problems don't occur. And I see that there version 1.4 of the VNC viewer is used, while on the Raspberry Pi4 it's version 1.3.
Thanks in advance for the support. :)
