### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by Malzmeier** [ich777/docker-thunderbird#18]
Hi,

I'm facing an issue on my long working thunderbird container.
When trying to connect I only receive the red message "Failed to connect to server". It has been working for month.

I'm updating the container using watchtower and the container has been updated automatically on July 10th.
Except the update nothing changed on my server.

Could it be an issue in the new docker image?

Here's the docker log:
```
---Ensuring UID: 99 matches user---
---Ensuring GID: 100 matches user---
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Checking configuration for noVNC---
Nothing to do, noVNC resizing set to default
Nothing to do, noVNC qaulity set to default
Nothing to do, noVNC compression set to default
---Taking ownership of data...---
---Starting...---
---Preparing Server---
---Resolution check---
---Checking for old logfiles---
---Checking for old display lock files---
---Starting Xvfb server---
---Starting x11vnc server---
---Starting Fluxbox---
---Starting noVNC server---
WebSocket server settings:
  - Listen on :8080
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
---Starting Thunderbird---
[GFX1-]: glxtest: libpci missing
[Parent 85, Main Thread] WARNING: Failed to execute child process “update-desktop-database” (No such file or directory): 'glib warning', file ./toolkit/xre/nsSigHandlers.cpp:167

(thunderbird-default:85): GLib-GIO-WARNING **: 14:10:43.293: Failed to execute child process “update-desktop-database” (No such file or directory)
```

And this is my docker compose:
```
version: '3'
services:
  thunderbird:
    container_name: thunderbird
    image: ich777/thunderbird
    #ports:
      #- 8080:8080
    volumes:
      - /opt/docker/thunderbird:/thunderbird
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thunderbird.entrypoints=https"
      - "traefik.http.routers.thunderbird.rule=Host(`thunderbird.xxx.xx`)"
      - "traefik.http.routers.thunderbird.tls=true"
      - "traefik.http.routers.thunderbird.middlewares=default@file"
      - "traefik.http.services.thunderbird.loadbalancer.server.port=8080"
      - "traefik.http.routers.thunderbird.service=thunderbird"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: "unless-stopped"
    networks:
      proxy:
      
networks:
  proxy:
    external: true
```
