### ISSUE TITLE
"latest" version newer than my desktop version & unsupported by add-ons

### ISSUE THREAD

**Issue by imthekaiser** [ich777/docker-thunderbird#19]
Thanks for building this container!  I'm wondering if there is a way to use anything other than latest and beta for the branch?

I'm getting this warning in TB:
![image](https://github.com/user-attachments/assets/df1cdbc2-1f76-4543-ac5b-a284e13e6dcd)

Also, some of my extensions are not compatible with the latest branch of TB.

So my question is if I can force the "stable" build?

**Comment by ich777** [comment]
Can you please share a bit more information on that?
What version, what architecture,…
Are you also sure that the container is on the latest version?

Your `docker run` command would be also good to know.

What version do you want to use?

**Comment by imthekaiser** [comment]
Sure.  I'm on unraid using docker compose on x86.  Docker compose is below.  I just installed today, container is up to date.

The thunderbird version running inside of the container is 131.0
Looks like the latest stable version I download from the official thunderbird.net website is 128.3.0esr  (win & linux)  That's what I'm running on my win 11 x86 laptop.

```
  thunderbird:
    container_name: thunderbird
    image: ich777/thunderbird
    cpuset: "14-15,30-31"
    restart: unless-stopped
    environment:
      - THUNDERBIRD_V=latest
      - THUNDERBIRD_LANG=en-US
      - TURBOVNC_PARAMS=-securitytypes none
      - CUSTOM_RES_W=1920
      - CUSTOM_RES_H=1080
      - UID=99
      - GID=100
      - UMASK=000
      - DATA_PERM=770
    volumes:
      - /mypath:/thunderbird
    # ports:
    #   - 8080:8080      
    networks:
      nginx_thunderbird:
```
