### ISSUE TITLE
Cannot use addprefix when behind Traefik 2

### ISSUE THREAD

**Issue by gcraenen** [ich777/docker-thunderbird#4]
Created a compose snippet as part of a larger docker-compose. When starting with traefik labels only pointing to http://server:ip this works but starts in a dir where I have to click vnc.html and click connect in the no-vnc screen.

When using traefiks addprefix labels to connect to http://server:ip/vnc.html?autoconnect=true I am getting:

```
Error response

Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.
```
This is the docker-compose snippet I am using:

```
#Thunderbird
  thunderbird:
    image: ich777/thunderbird
    container_name: thunderbird
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #port:
    #  - 8080:8080
    volumes:
      - $DOCKERDIR/appdata/thunderbird:/thunderbird
    environment:
      UID: $PUID
      GID: $PGID
      UMASK: 000
      DATA_PERM: 770
      CUSTOM_RES_W: 1536
      CUSTOM_RES_H: 864
      THUNDERBIRD_V: latest
      THUNDERBIRD_LANG: en-US
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      #HTTP Routers
      - "traefik.http.routers.thunderbird-rtr.entrypoints=https"
      - "traefik.http.routers.thunderbird-rtr.rule=Host(`thunderbird.$DOMAINNAME0`)"
      #Middlewares
      #- "traefik.http.routers.thunderbird-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.thunderbird-rtr.middlewares=chain-authelia@file,add-thunderbird"
      - "traefik.http.middlewares.add-thunderbird.addPrefix.prefix=/vnc.html?autoconnect=true"
      #HTTP Services
      - "traefik.http.routers.thunderbird-rtr.service=thunderbird-svc"
      - "traefik.http.services.thunderbird-svc.loadbalancer.server.port=8080"
```
